spring:
  batch:
    job:
      enabled: false
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        search:
          schema_management:
            strategy: drop-and-create-and-drop
          backend:
            type: elasticsearch
            analysis:
              configurer: ca.uhn.fhir.jpa.search.elastic.HapiElasticsearchAnalysisConfigurer
            protocol: http
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

hapi:
  fhir:
    server:
      url: "http://localhost:8888"
    version: r4

logging:
  level:
    root: info
    org.hibernate: off
    org.quartz: off
